#!/usr/bin/env bash
# domainscan enumerate a domain
# Copyright (C) 2020 Lucas Henry

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

sublist3r -d $1 -o $1.domains
dig +noall +answer $(cat $1.domains) > $1.ips
cat $1.ips
