#!/usr/bin/env bash
# enum is a small script that run enum scripts against an url
# Copyright (C) 2020 Lucas Henry

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

source config.sh
clear
echo "Scan using nikto started"
sudo nikto -h $1 -Tuning x > $1.nikto.txt &
$TERM_EXT_RUN "tail -f $(pwd)/$1.nikto.txt" &

echo "Scan using gobuster started"
gobuster dir -u $1 -w $DIR_WORDLIST -b 301 > $1.gobuster.txt &
